export const WORD_LIST: string[] = [
  'APPLE','MANGO','GRAPE','LEMON','LIME','PEACH','PLUM','PEAR',
  'MELON','BERRY','KIWI','FIG','DATE','GUAVA','PAPAYA','LYCHEE',
  'OLIVE','CHERRY','ORANGE','BANANA','LOTUS','ROSE','TULIP','IRIS',
  'DAISY','FERN','PALM','CEDAR','MAPLE','OAK','ASH','ELM',
  'PINE','BIRCH','WILLOW','CORAL','AMBER','JADE','RUBY','ONYX',
  'OPAL','TOPAZ','PEARL','IVORY','EBONY','SANDY','AZURE','CRIMSON',
  'TEAL','INDIGO','VIOLET','CYAN','SCARLET','GOLDEN','SILVER','BRONZE',
  'COPPER','MAROON','NAVY','MINT','SAGE','DUNE','REEF','CREEK',
  'CREST','BROOK','CLIFF','GROVE','BLAZE','STORM','CLOUD','MIST',
  'FROST','FLAME','SPARK','EMBER','GALE','TIDE','WAVE','COVE',
  'VALE','RIDGE','PEAK','GLEN','DELL','FORD','KNOLL','MOOR',
  'SHIRE','HEATH','MARSH','BAYOU','DELTA','DUSK','DAWN','NOON',
  'NIGHT','STAR','COMET','ORBIT','SOLAR','LUNAR','NOVA','ZENITH',
  'TIGER','EAGLE','FALCON','HAWK','RAVEN','CRANE','HERON','SWIFT',
  'WREN','FINCH','ROBIN','LARK','DOVE','IBIS','EGRET','MARTIN',
  'OWL','KITE','BUNNY','FOX','WOLF','BEAR','LYNX','PANDA',
  'COBRA','GECKO','SABLE','TAWNY','DUSKY','MOCHA','HAZEL','OCHRE',
  'TAUPE','UMBER','SIENNA','BISQUE','ALMOND','WALNUT','MINK','SLATE',
  'STONE','FLINT','SHALE','ALPHA','BRAVO','ECHO',
]

export function generateCode(): string {
  return WORD_LIST[Math.floor(Math.random() * WORD_LIST.length)]!
}
